# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
    
stages:
- stage: Build
  jobs:
  - job:
    variables: 
    - group: madday-backend-variables
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.200'
    - task: DotNetCoreCLI@2
      displayName: Install Lambda
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global Amazon.Lambda.Tools --framework netcoreapp3.1'
    - task: DotNetCoreCLI@2
      displayName: Package Function
      inputs:
        command: 'custom'
        custom: 'lambda'
        arguments: 'package --configuration Release --framework netcoreapp3.1 --output-package $(Build.ArtifactStagingDirectory)/MAD_days.zip'


    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'MAD_days.zip'
        publishLocation: 'Container'

- stage: Deploy
  jobs: 
    - job:

      variables:
      - group: AWS

      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'MAD_days.zip'
          downloadPath: '$(System.ArtifactsDirectory)'
      - script: chmod 644 $(find . -type f)
      - script: chmod 755 $(find . -type d)
      - task: LambdaDeployFunction@1
        displayName: 'Deploy Lambda Function'
        inputs:
          awsCredentials: 'AWS Root'
          regionName: 'eu-west-2'
          deploymentMode: 'codeandconfiguration'
          functionName: 'MyFunctionCreateFromAzureDevops'
          description: 'From AzureDevops'
          functionHandler: 'CsharpHandlers::AwsDotnetCsharp.GetHandler::GetAllOpportunities'
          runtime: 'dotnetcore3.1'
          codeLocation: 'localfile'
          localZipFile: '$(Build.ArtifactStagingDirectory)/MAD_days.zip'
          roleARN: '$(AWS-Lambda-ARN)'
  dependsOn:
  - Build
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))