service: back-end
frameworkVersion: '2'

provider:
  name: aws
  runtime: dotnetcore3.1
  profile: Serverless
  lambdaHashingVersion: 20201221
  region: eu-west-2

package:
  individually: true

functions:
  get-opportunity:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::GetOpportunity

    package:
      artifact: bin/Release/netcoreapp3.1/MAD_days.zip
    events:
      - httpApi:
          path: /opportunities/{id}
          method: get
  save-opportunity:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::SaveOpportunity

    package:
      artifact: bin/Release/netcoreapp3.1/MAD_days.zip
    events:
      - httpApi:
          path: /opportunities/{id}
          method: post
  